### ISSUE TITLE
Segfault when tracking in TOSCA field maps when using gcc-10

### ISSUE THREAD

**Issue by marionvanwelde** [chernals/zgoubido#23] opened 2020-10-05 09:41 UTC

**Comment by rtesse** [comment] 2020-10-27 23:06
Please attach a minimalistic example.

**Comment by rtesse** [comment] 2021-01-14 13:14
Here is the zgoubi.dat file:

```
tosca_test
'OBJET' BUNCH                                                                                                
3.465931267717e+03
2.00
1 1
0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 O
1
 
'TOSCA' tosca                                                                                                
0 2
1.000000000000e+00 1.000000000000e+00 1.000000000000e+00 1.000000000000e+00
FIELDMAP
6000 200 3 1.0
Cartesian_Y_-1_cm.table
Cartesian_Y_0_cm.table
Cartesian_Y_1_cm.table
0 1.000000000000e+00 1.000000000000e+00 1.000000000000e+00
25
1.000000000000e+00
2 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00
 
'END' 5dd5e8a236c24f8aad67
```

Here is the link to the field maps: https://owncloud.ulb.ac.be/index.php/s/D6NC2JzfkqNEm9N

**Comment by rtesse** [comment] 2022-05-13 12:29
By testing this issue again, it seems that the problem is solved and does not give any error with GCC-10 and GCC-11. @marionvanwelde, could you test on your side to confirm that there are no more problems?

**Comment by rtesse** [comment] 2023-03-20 10:22
Closing this issue as I cannot reproduce the bug with gfortran9, 10, 11 and 12

**Closed as completed by rtesse** 2023-03-20 10:22 UTC
Labels: zgoubi
